[profile.default]
solc-version = '0.8.23' 
[profile.zksync] 
zksolc = "1.5.11"
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
