[profile.default]
solc-version = '0.8.23' 
src = "src"
out = "out"
libs = ["lib"]
[profile.zksync] 
zksolc = "1.5.11"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
[fmt]
line_length = 80            
tab_width = 4                       
number_underscore = "thousands"  
multiline_func_header = "params_first_multi" 
wrap_comments = true
single_line_statement_blocks = "single"
contract_new_lines = true